### ISSUE TITLE
keep track of the user after installing app

### ISSUE THREAD

**Issue by Xalbi** [HubSpot/oauth-quickstart-nodejs#3]
Hello,

I saw in this example that i can use session to keep track of the user who install my app.

But is it possible to send a custom_field with in the install URI and get it back along with the 'code' in the callback.

Or is there another way to keep track of the user without using sessions.

FYI: am under a stateless microservice architecture.

thnx :)

**Comment by egoodhall** [comment]
Hey @Xalbi, thanks for reaching out. If you include a `state` query parameter in the authorization URL, the same value will get added as a `state` query parameter when HubSpot makes a request to the redirect URI with the authorization code.

For example, if your authorization URL looks like (note the `&state=abcd1234` at the end of the URL):
```
https://app.hubspot.com/oauth/authorize?client_id=xxxxxxxxxx&client_secret=xxxxxxxxxx&scope=contacts&redirect_uri=https://example.com/oauth&state=abcd1234
```
Then HubSpot would send a request to:
```
https://example.com/oauth?code=xxxxxxxxxx&state=abcd1234
```
once the user has granted permissions to your integration. You can read more about it in the Optional parameters section here: https://developers.hubspot.com/docs/methods/oauth2/initiate-oauth-integration

**Comment by Xalbi** [comment]
@emm035 Thats perfect, Thank you very much :+1:
