### ISSUE TITLE
An unexpected error occurred: "https://npm.hubteam.com/npm-nexus/repository/npm-all/dotenv/-/dotenv-6.0.0.tgz: ETIMEDOUT"

### ISSUE THREAD

**Issue by louischausse** [HubSpot/oauth-quickstart-nodejs#8]
Hello,

When I run the command yarn install nothing happens and then I get this error:

An unexpected error occurred: "https://npm.hubteam.com/npm-nexus/repository/npm-all/dotenv/-/dotenv-6.0.0.tgz: ETIMEDOUT"

I'm I the only one getting this error?

**Comment by egoodhall** [comment]
Hey @louischausse, thanks for reaching out. It looks like this is an issue coming from the yarn lockfile - I'll make a fix for this today

**Comment by egoodhall** [comment]
Hey @louischausse, this should be all taken care of

**Comment by louischausse** [comment]
It worked thanks!
